# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-04 12:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('reports', '0006_document_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupReports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ManyToManyField(to='auth.Group')),
                ('report_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.report')),
            ],
        ),
    ]
