# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-04 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('groupmanagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupreports',
            name='group',
        ),
        migrations.AddField(
            model_name='groupreports',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='groupreports',
            name='report_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.report'),
        ),
    ]
