# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-04 19:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(default='document', upload_to='documents/')),
                ('name', models.CharField(default='name', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='title', max_length=200, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('short_description', models.CharField(max_length=30)),
                ('detailed_description', models.CharField(max_length=200)),
                ('is_private', models.BooleanField(default='False')),
                ('location', models.CharField(default='Virginia', max_length=100)),
                ('is_encrypted', models.BooleanField(default='False')),
                ('username_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='folder',
            name='added_reports',
            field=models.ManyToManyField(to='reports.report'),
        ),
        migrations.AddField(
            model_name='folder',
            name='username_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='report_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.report'),
        ),
    ]
