# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='is_encrypted',
        ),
        migrations.AddField(
            model_name='document',
            name='is_encrypted',
            field=models.BooleanField(default='False'),
        ),
    ]
