# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-06 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20161205_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
