# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-04 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20161203_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='document',
        ),
        migrations.AddField(
            model_name='report',
            name='documents',
            field=models.FileField(default='document', upload_to='documents/'),
        ),
    ]
