# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-04 01:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20161204_0134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='documents',
            new_name='document',
        ),
    ]
