# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-04 02:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20161204_0135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(default='document', upload_to='documents/')),
            ],
        ),
        migrations.RemoveField(
            model_name='report',
            name='document',
        ),
        migrations.AddField(
            model_name='document',
            name='report_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.report'),
        ),
    ]
