# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-04 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_auto_20161204_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(default='name', max_length=100),
        ),
    ]
