# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='isSuspended',
            field=models.BooleanField(default=False),
        ),
    ]
