# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-04 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_userprofile_privatekey'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='rPrivKey',
            field=models.CharField(default=1, max_length=1024),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rPubKey',
            field=models.CharField(default=1, max_length=1024),
        ),
    ]
